### PR TITLE
Fix of trigger and gui

### PR DESCRIPTION
**Pull request by ByteCorum**
Your program is really very cool, I have been looking for something like this for a long time, thanks to the authors. I want to help as much as I can

### CODE REVIEW

**Comment by CowNowK** [comment]
ignore must not be fixed, the files are useless

**Comment by ByteCorum** [comment]
I fixed #242 in new commit

**Comment by NeverloseMLN** [comment]
可以帮我看看这个是什么原因不能编译吗
微信截图_20240407151117
微信截图_20240407151213

**Review by ByteCorum — COMMENTED** [review]
This code fixed the bot trigger delay, and minor problems with the graphical interface and added visual studio debugging directories to gitignore

**Pull request merged**
