### PR TITLE
Issue Bot

### PR DESCRIPTION
**Pull request by Wuemeli**
I've recently ridden the issues, and many of them can be fixed by simply using the latest Autobuild. In this PR, it will use a GitHub Action to autocomment on each issue.

Also, please ignore the CodeQL.

### CODE REVIEW

**Comment by Wuemeli** [comment]
@M3351AN

**Review by ByteCorum — CHANGES_REQUESTED** [review]
it gonna be better to use `actions/github-script@v5`. Also, u can use var to store text like: `const text = ''`

**Comment by ByteCorum** [comment]
it gonna be better to use actions/github-script@v5. Also, u can use var to store text like: const text = ''

**Review by ByteCorum — APPROVED** [review]
Nice

**Comment by Wuemeli** [comment]
@CowNowK @M3351AN

**Pull request closed without merging**
